---
- name: Cleanup stale hosts from AWX not present in NetBox
  hosts: localhost
  gather_facts: false

  vars:
    netbox_api_url: "{{ lookup('env', 'NETBOX_API') }}/api/dcim/devices/"
    netbox_vm_api_url: "{{ lookup('env', 'NETBOX_API') }}/api/virtualization/virtual-machines/"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    awx_api_url: "{{ lookup('env', 'AWX_API_URL') }}"
    awx_token: "{{ lookup('env', 'AWX_API_TOKEN') }}"
    awx_inventory_id: "5"
    netbox_filters: "&status=active&cf_mon_required=true&has_primary_ip=true&platform__isnull=false&custom_fields__zabbix_template_name__empty=false&custom_fields__sla_report_code__isnull=false"

  tasks:

    - name: Validate required vars
      assert:
        that:
          - netbox_api_url is defined
          - netbox_token is defined
          - awx_api_url is defined
          - awx_token is defined
          - awx_inventory_id is defined
        fail_msg: "Required API variables are not defined"

    - name: Get devices from NetBox
      uri:
        url: "{{ netbox_api_url }}?limit=1000{{ netbox_filters }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
        method: GET
        return_content: true
        validate_certs: false
      register: netbox_devices
      failed_when: netbox_devices.status != 200

    - name: Get VMs from NetBox
      uri:
        url: "{{ netbox_vm_api_url }}?limit=1000{{ netbox_filters }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
        method: GET
        return_content: true
        validate_certs: false
      register: netbox_vms
      failed_when: netbox_vms.status != 200

    - name: Debug NetBox device response
      debug:
        var: netbox_devices

    - name: Extract AWX hostnames and IDs
      set_fact:
        awx_host_map: >-
          {{
            dict(awx_hosts.json.results | map(attribute='name') | zip(awx_hosts.json.results | map(attribute='id')))
          }}

    - name: Identify stale AWX hosts
      set_fact:
        stale_hosts: >-
          {{
            awx_host_map.keys() | difference(netbox_hostnames)
          }}

    - name: Delete stale hosts from AWX
      uri:
        url: "{{ awx_api_url }}/api/v2/hosts/{{ awx_host_map[item] }}/"
        headers:
          Authorization: "Bearer {{ awx_token }}"
        method: DELETE
        validate_certs: false
      loop: "{{ stale_hosts }}"
      loop_control:
        label: "{{ item }}"
      when: stale_hosts | length > 0
