---
- name: Cleanup stale hosts from AWX not present in NetBox
  hosts: localhost
  gather_facts: false

  vars:
    netbox_api_url: "{{ lookup('env', 'NETBOX_API') }}/api/dcim/devices/"
    netbox_vm_api_url: "{{ lookup('env', 'NETBOX_API') }}/api/virtualization/virtual-machines/"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    awx_api_url: "{{ lookup('env', 'AWX_API_URL') }}"
    awx_token: "{{ lookup('env', 'AWX_API_TOKEN') }}"
    awx_inventory_id: "5"
    netbox_filters: "&status=active&cf_mon_required=true&has_primary_ip=true&platform__isnull=false&custom_fields__zabbix_template_name__empty=false&custom_fields__sla_report_code__isnull=false"

  tasks:

    - name: Validate required vars
      assert:
        that:
          - netbox_api_url is defined
          - netbox_token is defined
          - awx_api_url is defined
          - awx_token is defined
          - awx_inventory_id is defined
        fail_msg: "Required API variables are not defined"

    - name: Get devices from NetBox
      uri:
        url: "{{ netbox_api_url }}?limit=1000{{ netbox_filters }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
        method: GET
        return_content: true
        validate_certs: false
      register: netbox_devices
      failed_when: netbox_devices.status != 200

    - name: Get VMs from NetBox
      uri:
        url: "{{ netbox_vm_api_url }}?limit=1000{{ netbox_filters }}"
        headers:
          Authorization: "Token {{ netbox_token }}"
        method: GET
        return_content: true
        validate_certs: false
      register: netbox_vms
      failed_when: netbox_vms.status != 200

    - name: Combine NetBox hostnames
      set_fact:
        netbox_hostnames: >-
          {{
            (
              netbox_devices.json.results | map(attribute='name') | list
            ) + (
              netbox_vms.json.results | map(attribute='name') | list
            )
          }}

    - name: Get hosts from AWX inventory
      uri:
        url: "{{ awx_api_url }}/api/v2/hosts/?inventory={{ awx_inventory_id }}&page_size=1000"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        return_content: true
        status_code: 200
        validate_certs: false
      register: awx_hosts
      delegate_to: localhost
      failed_when: awx_hosts.status != 200

    - name: Extract AWX hostnames and IDs
      set_fact:
        awx_host_map: >-
          {{
            dict(awx_hosts.json.results | map(attribute='name') | zip(awx_hosts.json.results | map(attribute='id')))
          }}

    - name: Identify stale AWX hosts
      set_fact:
        stale_hosts: >-
          {{
            awx_host_map.keys() | difference(netbox_hostnames)
          }}

    - name: Attempt to delete stale host from AWX
      uri:
        url: "{{ awx_api_url }}/api/v2/hosts/{{ awx_host_map[item] }}/"
        headers:
          Authorization: "Bearer {{ awx_token }}"
        method: DELETE
        status_code: [200, 204, 409]
        validate_certs: false
      loop: "{{ stale_hosts }}"
      loop_control:
        label: "{{ item }}"
      register: delete_attempts
      failed_when: false

    - name: Force delete hosts that returned 409 Conflict
      uri:
        url: "{{ awx_api_url }}/api/v2/hosts/{{ awx_host_map[item.item] }}/"
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        method: DELETE
        body_format: json
        body:
          force: true
        status_code: [200, 204]
        validate_certs: false
      loop: "{{ delete_attempts.results | selectattr('status', 'equalto', 409) | list }}"
      loop_control:
        label: "{{ item.item }}"
      when: delete_attempts.results | selectattr('status', 'equalto', 409) | list | length > 0

    - name: Log failed forced deletions
      debug:
        msg: "Failed to force delete host: {{ item.item }}"
      when: item.status != 200 and item.status != 204
      loop: "{{ delete_attempts.results }}"

