---
- name: Compare AWX Inventory with Zabbix and safely update cmdb tag
  hosts: localhost
  gather_facts: false
  vars:
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
  tasks:
    - name: Get all hosts from Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            output: ["hostid", "host", "tags"]
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      register: zabbix_hosts

    - name: Set list of inventory hostnames (lowercase, no localhost)
      set_fact:
        inventory_hosts_lc: "{{ groups['all'] | difference(['localhost']) | map('lower') | list }}"

    - name: Prepare tag update info for each host (preserve unrelated tags)
      set_fact:
        zabbix_tag_updates: "{{ zabbix_tag_updates | default([]) + [ {
          'hostid': item.hostid,
          'host': item.host,
          'existing_tags': (
            item.tags is defined and item.tags is sequence and item.tags is not string
              | ternary(
                  item.tags | rejectattr('tag', 'equalto', 'cmdb') | list,
                  []
                )
          ),
          'cmdb_value': (((item.host | lower) in inventory_hosts_lc) | ternary('true', 'false') | string)
        } ] }}"
      loop: "{{ zabbix_hosts.json.result }}"

    - name: Update Zabbix hosts with cmdb tag (preserve unrelated tags)
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.update"
          params:
            hostid: "{{ item.hostid }}"
            tags: "{{ (item.existing_tags if item.existing_tags is sequence and item.existing_tags is not string else []) + [ { 'tag': 'cmdb', 'value': item.cmdb_value | string } ] }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      loop: "{{ zabbix_tag_updates }}"
      loop_control:
        label: "{{ item.host }}"
