---
- name: Compare AWX Inventory with Zabbix and tag hosts, preserving existing tags
  hosts: localhost
  gather_facts: false
  vars:
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
  tasks:
    - name: Get all hosts from Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            output: ["hostid", "host", "tags"]
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      register: zabbix_hosts

    - name: Set list of inventory hostnames (lowercase, no localhost)
      set_fact:
        inventory_hosts_lc: "{{ groups['all'] | difference(['localhost']) | map('lower') | list }}"

    - name: Prepare Zabbix host tag updates (preserve existing tags)
      set_fact:
        zabbix_tag_updates: >-
          {{
            zabbix_hosts.json.result | map('combine', {
              'cmdb_value': (
                (item.host | lower) in inventory_hosts_lc | ternary('true', 'false')
              ),
              'existing_tags': (item.tags | default([]) | rejectattr('tag', 'equalto', 'cmdb') | list)
            }) | list
          }}

    - name: Tag Zabbix hosts with cmdb status (preserve existing tags)
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.update"
          params:
            hostid: "{{ item.hostid }}"
            tags: "{{ item.existing_tags + [ { 'tag': 'cmdb', 'value': item.cmdb_value } ] }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      loop: "{{ zabbix_tag_updates }}"
      loop_control:
        label: "{{ item.host }}"
