---
- name: Sync NetBox devices/VMs to Zabbix (CF groups, tags, proxy, groupid)
  hosts: all
  gather_facts: false

  vars:
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    apply_changes: false

  tasks:
    - name: Verify required env vars present
      assert:
        that:
          - zabbix_api_url is defined and zabbix_api_url | length > 0
          - zabbix_api_token is defined and zabbix_api_token | length > 0
        fail_msg: "ZABBIX_API_URL and/or ZABBIX_API_TOKEN are missing."

    - name: Ensure Zabbix template name is defined
      assert:
        that:
          - zabbix_template_name is defined
          - zabbix_template_name | length > 0
        fail_msg: "Missing Zabbix template name for {{ inventory_hostname }}"

    - name: Lookup primary Zabbix template ID by exact name
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers: { Content-Type: "application/json" }
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "template.get"
          params:
            output: ["templateid", "host"]
            filter:
              host: ["{{ zabbix_template_name }}"]
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      delegate_to: localhost
      register: zabbix_template_lookup
      failed_when:
        - zabbix_template_lookup.json.result | length == 0
        - zabbix_template_lookup.json.result | length > 1

    - name: Set primary template ID
      set_fact:
        template_id: "{{ zabbix_template_lookup.json.result[0].templateid }}"

    - name: Compute desired group id from NetBox CF (int; fallback to 5)
      set_fact:
        desired_groupid: "{{ (zabbix_group_id | default(5)) | int }}"

    - name: Verify desired host group exists and is visible
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers: { Content-Type: "application/json" }
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "hostgroup.get"
          params:
            output: ["groupid", "name"]
            groupids:
              - "{{ desired_groupid }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      delegate_to: localhost
      register: zbx_group_lookup

    - name: Determine effective group id
      set_fact:
        effective_groupid: "{{ (zbx_group_lookup.json.result | length > 0) | ternary(desired_groupid, 5) }}"

    - name: Determine proxy ID (if mapping provided)
      set_fact:
        proxy_id: "{{ site_to_proxy_mapping[site_id|string] | default(site_to_proxy_mapping['_default'] | default('')) }}"
      when: site_to_proxy_mapping is defined

    - name: Set proxy field
      set_fact:
        proxy_field: "{{ (proxy_id | length > 0) | ternary({'proxy_hostid': proxy_id}, {}) }}"
      when: proxy_id is defined

    - name: Get existing host
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers: { Content-Type: "application/json" }
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            output: ["hostid", "interfaces", "status"]
            filter:
              host: ["{{ inventory_hostname }}"]
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      delegate_to: localhost
      register: zabbix_host_check

    - name: Set host existence flags
      set_fact:
        host_exists: "{{ zabbix_host_check.json.result | length > 0 }}"
        host_missing: "{{ not host_exists }}"

    - name: Set tags and visible name
      set_fact:
        visible_name: >-
          {{ inventory_hostname }}{% if description is defined and description|length > 0 %} - {{ description | trim }}{% endif %}
        zabbix_tags: >-
          {%- set tags = [] -%}
          {%- set sla = sla_report_code | default(custom_fields.sla_report_code | default('unknown')) -%}
          {%- set _ = tags.append({"tag": "device", "value": sla|string }) -%}

          {%- set os_raw = ansible_network_os | default('') | lower -%}
          {%- set os_map = {
            'aoscx': 'arubaos-cx', 'aruba': 'arubaos-cx',
            'cisco': 'cisco-ios', 'forti': 'fortios',
            'synology': 'synology-dsm', 'apc': 'apc',
            'eaton': 'eaton', 'unifi': 'unifi',
            'ubiquiti': 'unifi', 'vmware': 'vmware-esxi',
            'esxi': 'vmware-esxi', 'windows': 'windows',
            'linux': 'linux', 'debian': 'linux', 'ubuntu': 'linux',
            'centos': 'linux', 'redhat': 'linux', 'rhel': 'linux'
          } -%}
          {%- set os_tag = os_map[os_map.keys() | select('in', os_raw) | list | first] | default('unknown') -%}
          {%- set _ = tags.append({"tag": "os", "value": os_tag }) -%}

          {%- set env = environment | default(custom_fields.environment | default('')) -%}
          {%- if env | length > 0 -%}
            {%- set _ = tags.append({"tag": "environment", "value": env }) -%}
          {%- endif -%}

          {%- if site_slug is defined -%}
            {%- set _ = tags.append({"tag": "site", "value": site_slug|string|lower }) -%}
          {%- endif -%}

          {%- set nbstat = status.value if status is mapping else status -%}
          {%- set _ = tags.append({"tag": "nb_status", "value": nbstat|string }) -%}

          {%- set _ = tags.append({"tag": "cmdb", "value": "true" }) -%}
          {{ tags }}

    - name: Set interface list
      set_fact:
        interface_list:
          - type: "{{ 2 if 'snmp' in zabbix_template_name | lower else 1 }}"
            main: 1
            useip: 1
            ip: "{{ ansible_host }}"
            dns: ""
            port: "{{ '161' if 'snmp' in zabbix_template_name | lower else '10050' }}"
            details: >-
              {{ {"version": 2, "community": "{$SNMP_COMMUNITY}"} if 'snmp' in zabbix_template_name | lower else omit }}

    - name: Set create params
      set_fact:
        zabbix_create_params: >-
          {{ {
            'host': inventory_hostname,
            'name': visible_name,
            'status': 0,
            'interfaces': interface_list,
            'groups': [ {'groupid': effective_groupid} ],
            'templates': [ {'templateid': template_id } ],
            'tags': zabbix_tags
          } | combine(proxy_field | default({})) }}
      when: host_missing

    - name: Set update params
      set_fact:
        zabbix_update_params: >-
          {{ {
            'hostid': zabbix_host_check.json.result[0].hostid,
            'name': visible_name,
            'status': 0,
            'groups': [ {'groupid': effective_groupid} ],
            'templates': [ {'templateid': template_id } ],
            'tags': zabbix_tags
          } | combine(proxy_field | default({})) }}
      when: host_exists

    - name: Create host
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers: { Content-Type: "application/json" }
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.create"
          params: "{{ zabbix_create_params }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      delegate_to: localhost
      when:
        - host_missing
        - apply_changes

    - name: Update host
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers: { Content-Type: "application/json" }
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.update"
          params: "{{ zabbix_update_params }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: false
      delegate_to: localhost
      when:
        - host_exists
        - apply_changes

    - name: Dry run message
      debug:
        msg: "apply_changes=false → dry run only; no host changes pushed"
      when: not apply_changes
