---
- name: Sync NetBox devices to Zabbix
  hosts: all
  gather_facts: false
  vars:
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"

  tasks:
    - name: Verify inventory data
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          IP: {{ ansible_host }}
          Description: "{{ description | default('Not provided') }}"
          Site ID: {{ site_id }}
          Site Slug: {{ site_slug }}
          Template Name: {{ zabbix_template_name }}"

    - name: Ensure Zabbix template name is defined
      assert:
        that:
          - zabbix_template_name is defined
          - zabbix_template_name | length > 0
        fail_msg: "Missing Zabbix template name for {{ inventory_hostname }}"

    - name: Lookup Zabbix template ID by name
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "template.get",
            "params": {
              "output": ["templateid"],
              "filter": {
                "host": "{{ zabbix_template_name }}"
              }
            },
            "auth": "{{ zabbix_api_token }}",
            "id": 1
          }
        validate_certs: no
      delegate_to: localhost
      register: zabbix_template_lookup
      failed_when: zabbix_template_lookup.json.result | length == 0

    - name: Set Zabbix template ID
      set_fact:
        template_id: "{{ zabbix_template_lookup.json.result[0].templateid }}"

    - name: Determine proxy ID
      set_fact:
        proxy_id: "{{ site_to_proxy_mapping[site_id | string] | default(site_to_proxy_mapping['_default']) }}"

    - name: Notify if no proxy is assigned
      debug:
        msg: "No Zabbix proxy assigned for {{ inventory_hostname }} (Site ID: {{ site_id }})"
      when: proxy_id | length == 0

    - name: Determine interface configuration
      set_fact:
        interface_config: |
          {% if 'agent' in zabbix_template_name | lower %}
          [ {
            "type": 1, "main": 1, "useip": 1, "ip": "{{ ansible_host }}", "dns": "", "port": "10050"
          } ]
          {% elif 'snmp' in zabbix_template_name | lower %}
          [ {
            "type": 2, "main": 1, "useip": 1, "ip": "{{ ansible_host }}", "dns": "", "port": "161",
            "details": { "version": 2, "community": "{$SNMP_COMMUNITY}" }
          } ]
          {% else %}
          [ {
            "type": 3, "main": 1, "useip": 1, "ip": "{{ ansible_host }}", "dns": "", "port": "623"
          } ]
          {% endif %}

    - name: Get existing host from Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "jsonrpc": "2.0",
            "method": "host.get",
            "params": {
              "output": ["hostid", "name", "proxy_hostid"],
              "filter": {
                "host": "{{ inventory_hostname }}"
              }
            },
            "auth": "{{ zabbix_api_token }}",
            "id": 1
          }
        validate_certs: no
      delegate_to: localhost
      register: zabbix_host_check

    - name: Set visible name
      set_fact:
        visible_name: "{{ inventory_hostname }}{% if description is defined and description|length > 0 %} - {{ description | trim }}{% endif %}"

    - name: Debug platform slug
      debug:
        msg: "DEBUG PLATFORM SLUG: {{ platform.slug | lower }}"

    - name: Set Zabbix host tags based on device role, site, and NetBox status
      set_fact:
        zabbix_tags: >-
          {%- set tags = [] -%}

          {# Device Role Tags #}
          {%- for role in device_roles | default([]) -%}
            {%- set normrole = role | lower -%}
            {%- if 'switch-core' in normrole -%}
              {%- set _ = tags.append({"tag": "device", "value": "switch core"}) -%}
            {%- elif 'switch-edge' in normrole -%}
              {%- set _ = tags.append({"tag": "device", "value": "switch edge"}) -%}
            {%- elif 'uninterruptible-power-supply' in normrole -%}
              {%- set _ = tags.append({"tag": "device", "value": "ups"}) -%}
            {%- endif -%}
          {%- endfor -%}

          {# If no device tag was added, set as unknown #}
          {%- if tags | selectattr('tag', 'equalto', 'device') | list | length == 0 -%}
            {%- set _ = tags.append({"tag": "device", "value": "unknown"}) -%}
          {%- endif -%}

          {# Manufacturer Tag from platform #}
          {%- if platform is defined and platform is not none %}
            {%- set plat = platform | lower %}
            {%- if 'apc_webos' in plat -%}
              {%- set _ = tags.append({"tag": "manufacturer", "value": "apc"}) -%}
            {%- elif 'eaton_webos' in plat -%}
              {%- set _ = tags.append({"tag": "manufacturer", "value": "eaton"}) -%}
            {%- elif 'aoscx' in plat -%}
              {%- set _ = tags.append({"tag": "manufacturer", "value": "aruba"}) -%}
            {%- elif 'cisco' in plat -%}
              {%- set _ = tags.append({"tag": "manufacturer", "value": "cisco"}) -%}
            {%- endif -%}
          {%- endif %}

          {# Site Tag #}
          {%- if site_slug is defined -%}
            {%- set _ = tags.append({"tag": "site", "value": site_slug | lower}) -%}
          {%- endif -%}

          {# NetBox Status Tag #}
          {%- set nbstat = status.value if status is mapping and status.value is defined else status -%}
          {%- set _ = tags.append({"tag": "nb_status", "value": nbstat }) -%}

          {{ tags }}

    - name: Set Zabbix host status based on device status
      set_fact:
        zabbix_host_status: >-
          {% if status in ['active', 'Active', 1, '1'] or (status.label | default('') | lower) == 'active' %}
            '0'
          {% else %}
            '1'
          {% endif %}

    - name: Build Zabbix host create params
      set_fact:
        zabbix_create_params: >-
          {{
            {
              "host": inventory_hostname,
              "name": visible_name,
              "interfaces": interface_config | from_yaml,
              "groups": [
                {"groupid": site_to_group_mapping[site_slug] | default(site_to_group_mapping['_default']) }
              ],
              "templates": [
                {"templateid": template_id }
              ]
            }
            | combine((proxy_id | length > 0) | ternary({"proxy_hostid": proxy_id}, {}), recursive=True)
            | combine((zabbix_tags | length > 0) | ternary({"tags": zabbix_tags}, {}), recursive=True)
          }}
      when: zabbix_host_check.json.result | length == 0

    - name: Build Zabbix host update params
      set_fact:
        zabbix_update_params: >-
          {{
            {
              "hostid": zabbix_host_check.json.result[0].hostid,
              "name": visible_name,
              "groups": [
                {"groupid": site_to_group_mapping[site_slug] | default(site_to_group_mapping['_default']) }
              ],
              "templates": [
                {"templateid": template_id }
              ]
            }
            | combine((proxy_id | length > 0) | ternary({"proxy_hostid": proxy_id}, {}), recursive=True)
            | combine((zabbix_tags | length > 0) | ternary({"tags": zabbix_tags}, {}), recursive=True)
          }}
      when:
        - zabbix_host_check.json is defined
        - zabbix_host_check.json.result is defined
        - zabbix_host_check.json.result | length > 0

    - name: Skip update if host doesn't exist
      debug:
        msg: "Skipping update: Host '{{ inventory_hostname }}' not found in Zabbix."
      when: zabbix_host_check.json.result | length == 0

    - name: Create new host in Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.create"
          params: "{{ zabbix_create_params }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: no
      delegate_to: localhost
      when: zabbix_host_check.json.result | length == 0

    - name: Update existing host in Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.update"
          params: "{{ zabbix_update_params }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        validate_certs: no
      delegate_to: localhost
      when: zabbix_host_check.json.result | length > 0
