---
- name: Cleanup Zabbix hosts with tag cmdb=true not in AWX inventory
  hosts: localhost
  gather_facts: false

  vars:
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    awx_inventory_hostnames: "{{ groups['all'] | default([]) }}"
    dry_run: true  # Set to false to actually delete hosts

  tasks:

    - name: Debug Zabbix connection variables
      debug:
        msg:
          - "API URL: {{ zabbix_api_url }}"
          - "Token: {{ zabbix_api_token | default('MISSING', true) }}"

    - name: Debug token length
      debug:
        msg: "Zabbix API token is {{ zabbix_api_token | length }} characters long"

    - name: Get all Zabbix hosts with tags
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        validate_certs: false
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            output: ["hostid", "host"]
            selectTags: "extend"
          auth: "{{ zabbix_api_token }}"
          id: 1
      register: all_zabbix_hosts
      delegate_to: localhost

    - name: Filter Zabbix hosts with tag cmdb=true
      set_fact:
        zabbix_cmdb_hosts: >-
          {{
            all_zabbix_hosts.json.result
            | selectattr('tags', 'defined')
            | selectattr('tags', 'select', 'tag == "cmdb" and value == "true"')
            | list
          }}

    - name: Extract orphaned hosts (in Zabbix but not in AWX)
      set_fact:
        orphaned_hosts: >-
          {{
            zabbix_cmdb_hosts.json.result
            | selectattr('host', 'defined')
            | rejectattr('host', 'in', awx_inventory_hostnames)
            | list
          }}

    - name: Show orphaned hosts that would be removed
      debug:
        msg: "Dry Run - would remove Zabbix host '{{ item.host }}' (ID {{ item.hostid }})"
      loop: "{{ orphaned_hosts }}"
      when: dry_run | bool
      loop_control:
        label: "{{ item.host }}"

    - name: Delete orphaned Zabbix hosts with cmdb=true (force delete)
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.delete"
          params: "{{ orphan_host_ids }}"
          auth: "{{ zabbix_api_token }}"
          id: 2
        status_code: [200]
        validate_certs: false
      register: delete_result
      when: not dry_run | default(false)
