- name: Cleanup Zabbix hosts with tag cmdb=true not in AWX inventory
  hosts: localhost
  gather_facts: false
  vars:
    zabbix_api_url: "{{ lookup('env', 'ZABBIX_API_URL') }}"
    zabbix_api_token: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
    awx_inventory_hostnames: "{{ groups['all'] | default([]) }}"
    dry_run: true

  tasks:
    - name: Get all Zabbix hosts with tags
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        validate_certs: false
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            output: ["hostid", "host"]
            selectTags: "extend"
          auth: "{{ zabbix_api_token }}"
          id: 1
      register: all_zabbix_hosts
      delegate_to: localhost

    - name: Build list of Zabbix hosts with cmdb=true tag
      set_fact:
        zabbix_cmdb_hosts: "{{ zabbix_cmdb_hosts | default([]) + [ item ] }}"
      loop: "{{ all_zabbix_hosts.json.result }}"
      when: >
        item.tags is defined and
        (item.tags | selectattr('tag', 'equalto', 'cmdb') | selectattr('value', 'equalto', 'true') | list | length > 0)

    - name: Extract orphaned hosts (in Zabbix but not in AWX)
      set_fact:
        orphaned_hosts: >-
          {{
            zabbix_cmdb_hosts
            | rejectattr('host', 'in', awx_inventory_hostnames)
            | list
          }}

    - name: Show orphaned hosts that would be removed
      debug:
        msg: "Dry Run - would remove Zabbix host '{{ item.host }}' (ID {{ item.hostid }})"
      loop: "{{ orphaned_hosts }}"
      when: dry_run | bool

    - name: Delete orphaned Zabbix hosts with cmdb=true (force delete)
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.delete"
          params: "{{ orphaned_hosts | map(attribute='hostid') | list }}"
          auth: "{{ zabbix_api_token }}"
          id: 2
        status_code: [200]
        validate_certs: false
      when: not dry_run | bool and orphaned_hosts | length > 0
